#!/usr/bin/env osascript -l JavaScript

var log = console.log

cleanTrackLists()

function cleanTrackLists(){
	iTunes = Application('iTunes')
	delay(.3)

	var cleancount = 0
	var albums = {}
	var files = {}
	var targetTracks = iTunes.libraryPlaylists[0].fileTracks();
	if(targetTracks.length>0){
		log('Now cleaning...');
		targetTracks.forEach(function(t){
			if(t.podcast()){
				return;
			}

			//clean by file location
			var loc = t.location()
			var cleanByFile = !loc || (loc && files[loc])

			//clean byname by same album
			var an = t.album()
			var cleanByNameInAlbum = (albums[an] ? albums[an] : (albums[an]={}))[t.name()]

			if(cleanByFile || cleanByNameInAlbum){
				iTunes.delete(t)
				cleancount++
			}else{
				files[loc] = t
				albums[an][t.name()] = t
			}
		})
	}else{
		log('Not found any songs in your itunes library.');
	}

	return cleancount
}
