#!/usr/local/bin/node

//config
var log = console.log.bind(console);
var fs = require('fs-extra');
var mkdirp = require('mkdirp');
var cho = require('chokidar');
var mime = require('mime');
var path = require('path');
var args = require('minimist')(process.argv.slice(2));
var params = args._;
var queue = require('queue');
require('shelljs/global');
var mv = require('mv');

//resolve args
if(args['h']){
	log('Usage: termini [options]... [preset] [PATH SRC] [PATH DEST]');
	log('\n')
	log('# Auto-import music files:\n > termini itunes [PATH SRC] [PATH to itunes music library]');
	log('# Restrict by mimetypes or extenstions:\n > termini --allow-mime-types=audio/mpeg,video/mp4 --allow-extensions=mp3,jpg,gif,mp4 [PATH SRC] [PATH DEST]');
	process.exit(code=0);
}

if(params.length<2){
	log('Usage: termini [options]... [preset] [PATH SRC] [PATH DEST]');
	process.exit(1);
}


var PATH_TARGET = params.length==3 ? params[1] :params[0];
var PATH_TO = params.slice(-1)[0];
var IS_PATH_TO_SELF = is_in_same_dir(PATH_TARGET, PATH_TO);

//init presets
var preset = params.length==3 ? params[0] : 'notdefined';
var preset_values = ({
	itunes : {
		// itunes supported types : mp3, aiff, wav, mp4, aac, m4a
		ext:['.mp3', '.aiff', '.wav', '.mp4', '.aac', '.m4a'],
		mime:['audio/aac', 'audio/mp4', 'audio/mpeg', 'audio/mp4a-latm', 'audio/x-wav', 'audio/x-aiff']
	}
})[preset];

//resolve mimetype, extension
var option_exts = args['allow-extensions'];
var option_mimes = args['allow-mime-types'];
var exts_by_option = option_exts && option_exts.split(',');
var exts_by_preset = preset_values && preset_values.ext;
var allowed_exts = exts_by_option && exts_by_preset ? exts_by_option.concat(exts_by_preset) : (exts_by_option || exts_by_preset);

var mimes_by_option = option_mimes && option_mimes.split(',');
var mimes_by_preset = preset_values && preset_values.mime;
var allowed_mimes = mimes_by_option && mimes_by_preset ? mimes_by_option.concat(mimes_by_preset) : (mimes_by_option || mimes_by_preset);

//init lists
var files_roots = {};

//queue config
var q = queue({timeout:3000, concurrency:true});
var wait_removal = 10 * 1000;

//watch
var watcher = cho.watch(PATH_TARGET, {
  persistent: true,
  recursive: true,
  ignoreInitial: true,
  usePolling: true,
  alwaysStat: false,
  depth: undefined,
  interval: 0,
  atomic: true
});

watcher.on('all', function(e,f) {
    var ext = path.extname(f);
	var valid_ext = allowed_exts ? allowed_exts.indexOf(ext.toLowerCase()) > -1 : true;

	var mt = mime.lookup(f);
	var valid_mime = allowed_mimes ? allowed_mimes.indexOf(mt) > -1 : true;

	var valid_format = valid_ext && valid_mime;

    var temp_origin_f = path.join(path.dirname(f), path.basename(f).replace(path.extname(f), ''));
    var temp_streaming = 'application/octet-stream'==mt && allowed_exts ? allowed_exts.indexOf(path.extname(temp_origin_f))>-1 : path.extname(temp_origin_f);

	var added = valid_format && e=='add';
	var addedDir = e=='addDir';
    var copied = valid_format && e=='change';
    var stream_completed = valid_format && e=='add';

	// compress_f(f,get_dest_f(f,PATH_TO));
	if(added || copied){
		if(fs.lstatSync(f).size){
			add_job_move_f(f, get_dest_f(f, PATH_TO));
		}
	}
});

/*
	[File Move]
*/

//queue
q.on('success', function(result, job) {

});

function add_job_move_f(target_f, dest_f) {
    var __op = function (cb) {
		try{
			log('copy', target_f, '->', dest_f);
			fs.copySync(target_f, dest_f);
		}catch(e){}
        cb();
    };

    if (q.length == 0) {
        q.push(__op);

		if(IS_PATH_TO_SELF){
			q.start();

		}else{
			q.start(function(err) {
				wait_remove_all(target_f);
	        });
		}
    }else{
        q.push(__op);
    }
}

function wait_remove_all(target_f){
    var target_f_root = get_target_root(target_f);
	//parent dir == PATH_TARGET
	if(!target_f_root){
		return;
	}

    var timeoutObj = files_roots[target_f_root];
    timeoutObj && clearTimeout(timeoutObj);
    timeoutObj = setTimeout(function(){
        delete files_roots[target_f_root];
        fs.remove(target_f_root, function(e){
            log('Done.', target_f_root);
        });
    }, wait_removal);
    files_roots[target_f_root] = timeoutObj;
}

/*
	[File Compress]
*/
function compress_f(target_f, dest_f){
	return exec(['svgo',target_f, dest_f].join(' '));
}

/*
	[Utils]
*/
function get_dest_f(f, dest_dir){
	return path.join(dest_dir, path.relative(PATH_TARGET, f));
}

function get_target_root(f){
	var f_root_dir = path.dirname(path.resolve(f)).replace(path.resolve(PATH_TARGET),'').split(path.sep)[1];
    return f_root_dir && !is_in_same_dir(f, PATH_TARGET) ? path.join(PATH_TARGET, f_root_dir) : null;
}

function is_in_same_dir(f, d){
	var rel = path.relative(f, d);
	return !rel || rel=='..';
}

var glob = require("glob");
function get_files_all(dir, exts, mimes){
	var files = [];
	var hasExtDef = Array.isArray(exts);
	var hasMimeDef = Array.isArray(mimes);

	function mkpatt_all(dir_path){
		return path.resolve(dir_path)+path.sep+'**/*.'+(hasExtDef ? '+('+exts.join('|')+')' : '*');
	}
	function rdpath_all(dir_path){
		glob.sync(mkpatt_all(dir_path)).forEach(function(f){
			var _stat = fs.lstatSync(f);
			if(_stat.isDirectory()){
				// rdpath_all(f);
			}else if(_stat.isFile() && (hasMimeDef ? mimes.indexOf(mime.lookup(f))>-1 : true)){
				files.push(f);
			}
		});
	}
	rdpath_all(dir);
	return files;
}

log('Start watching...',PATH_TARGET, '->', PATH_TO);
