#!/bin/bash
source $(dirname $0)/xcpd-shared

if [ "$1" == "--exclude-new-buildnum" ]; then
	BUILD_NUM=$(agvtool what-version | tail -2 | awk '{ print $1, $2 }')
	read  -rd '' BUILD_NUM <<< "$BUILD_NUM"
else
	BUILD_NUM=$(agvtool next-version -all | tail -3 | awk 'NF{print $NF; exit}')
fi

re='^[0-9]+$'
if ! [[ $BUILD_NUM =~ $re ]] ; then
   echo "error: Can't Extract build number." >&2; exit 1
fi

echo "============ NOW DEPLOY TO ORIGIN : Build $BUILD_NUM ============"

# push to origin
git add -u
git commit -m "[Build $BUILD_NUM - Beta]"
git push -f origin develop:release-beta
git push origin develop

# undo stash
STASHED_ID=$(get_tmp_stash_id)
if [ -n "$STASHED_ID" ]; then
	if [ -n "$(git stash pop "$STASHED_ID" --index | egrep "Dropped $STASHED_ID")" ]; then
		echo "Restored working directory and index state succesfully."
	fi
fi
